[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "haproxy.tmpl"

# The location to place the rendered configuration file
dest = "/etc/haproxy/haproxy.cfg"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ 
"/registry/services/endpoints/kube-system",
] 

# File ownership and mode information
owner = "root"
mode = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
check_cmd = "/usr/local/sbin/haproxy -c -q -f {{ .src }}"
# reload_cmd = "echo '[kubernetes-endpoint-proxy] Reloading HAProxy'; pkill haproxy"
reload_cmd = "/usr/local/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf `cat /var/run/haproxy.pid`"
